### ISSUE TITLE
terminal参数指定问题

### ISSUE THREAD

**Issue by Zrzzzz** [matrix1001/welpwn#14]
```
    context.log_level = 'debug'
    context.terminal = ['tmux', 'splitw', '-h'] 
    # ctx.debug_remote_libc = True
    if args.G:
        rs('gdb', gdbscript='b read\nc')
    elif args.R:
        rs('remote')
    else:
        rs()
```
代码如上，使用命令`python exp.py G`
会报错
```
Traceback (most recent call last):
  File "exp.py", line 82, in <module>
    main()
  File "exp.py", line 50, in main
    rs('gdb', gdbscript='b read\nc')
  File "exp.py", line 36, in <lambda>
    rs      = lambda *args, **kwargs    :ctx.start(*args, **kwargs)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/welpwn-0.97-py3.8.egg/PwnContext/core.py", line 344, in start
    self.io = binary.debug(**kwargs)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/pwntools-4.9.0b0-py3.8.egg/pwnlib/elf/elf.py", line 459, in debug
    return pwnlib.gdb.debug([self.path] + argv, *a, **kw)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/pwntools-4.9.0b0-py3.8.egg/pwnlib/context/__init__.py", line 1578, in setter
    return function(*a, **kw)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/pwntools-4.9.0b0-py3.8.egg/pwnlib/gdb.py", line 580, in debug
    tmp = attach((host, port), exe=exe, gdbscript=gdbscript, ssh=ssh, sysroot=sysroot, api=api)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/pwntools-4.9.0b0-py3.8.egg/pwnlib/context/__init__.py", line 1578, in setter
    return function(*a, **kw)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/pwntools-4.9.0b0-py3.8.egg/pwnlib/gdb.py", line 1048, in attach
    gdb_pid = misc.run_in_new_terminal(cmd, preexec_fn = preexec_fn)
  File "/root/miniconda3/envs/pwn/lib/python3.8/site-packages/pwntools-4.9.0b0-py3.8.egg/pwnlib/util/misc.py", line 409, in run_in_new_terminal
    pid = int(out)
ValueError: invalid literal for int() with base 10: b''

```

**Comment by sln-1550** [comment]
这个不是源码的问题，只是你没有先用tmux进入shell
